CREATE TABLE IF NOT EXISTS clients (
    id VARCHAR(255) PRIMARY KEY,
    secret VARCHAR(255),
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    home_url VARCHAR(255) NOT NULL,
    callback_url VARCHAR(255),
    privileges VARCHAR(100) DEFAULT 'all',
    auto_verify TINYINT DEFAULT 1,
    public TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    project_id VARCHAR(40),
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);